In [22]:
# Importing required libraries
import nltk
import pandas as pd
import numpy as np

### StopWords


In [23]:
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\PrathameshDhande\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\PrathameshDhande\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\PrathameshDhande\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\PrathameshDhande\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [24]:
from nltk.corpus import stopwords
stopwords.words("english")

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

### Tokenization

In [25]:
from nltk.tokenize import word_tokenize, sent_tokenize

sentence1: str = "Hello i m Prathamesh Dhande."
word_tokenize(sentence1)

['Hello', 'i', 'm', 'Prathamesh', 'Dhande', '.']

In [26]:
paragraphs = "These is the sentence 1. These is the sentence 2."
sent_tokenize(paragraphs)

['These is the sentence 1.', 'These is the sentence 2.']

### Lemmatization

In [27]:
from nltk.stem import WordNetLemmatizer,PorterStemmer

In [28]:
para1 = "I m runs in the snow and plays with the winds air"
word_lemmatize:WordNetLemmatizer = WordNetLemmatizer()

for words in word_tokenize(para1):
    print(word_lemmatize.lemmatize(words))

I
m
run
in
the
snow
and
play
with
the
wind
air


### Stemming

In [29]:
porter_stem = PorterStemmer()
for words in word_tokenize(para1):
    print(porter_stem.stem(words))

i
m
run
in
the
snow
and
play
with
the
wind
air


### OneHot Encoding

In [30]:
from sklearn.preprocessing import OneHotEncoder

In [31]:
data = pd.DataFrame({
    "Price": [100, 200, 300, 400, 500],
    "Gender": ["Male", "Female", "Male", "Male", "Female"]
})
data

Price  Gender
0    100    Male
1    200  Female
2    300    Male
3    400    Male
4    500  Female

In [32]:
onehotencoding = OneHotEncoder(sparse_output=False, dtype=int)
categorical_columns = data.select_dtypes("object")
gender_encoded = onehotencoding.fit_transform(categorical_columns)
gender_encoded

array([[0, 1],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0]])

In [33]:
one_hot_dataframe = pd.DataFrame(
    gender_encoded, columns=onehotencoding.get_feature_names_out())
one_hot_dataframe

Gender_Female  Gender_Male
0              0            1
1              1            0
2              0            1
3              0            1
4              1            0

In [34]:
concatedpd = pd.concat([data, one_hot_dataframe], axis=1)

In [35]:
concatedpd

Price  Gender  Gender_Female  Gender_Male
0    100    Male              0            1
1    200  Female              1            0
2    300    Male              0            1
3    400    Male              0            1
4    500  Female              1            0

### Bag of Words

In [36]:
from sklearn.feature_extraction.text import CountVectorizer

data = pd.DataFrame({
    "text": ["Watch the Movie", "Have you Watch the Movie", "Watch the Movie Watch the Movie"]
})

count_vect = CountVectorizer()
vectorized = count_vect.fit_transform(data["text"])

print(count_vect.vocabulary_)
print(vectorized.toarray())

{'watch': 3, 'the': 2, 'movie': 1, 'have': 0, 'you': 4}
[[0 1 1 1 0]
 [1 1 1 1 1]
 [0 2 2 2 0]]


### N-Grams

In [37]:
count_vect = CountVectorizer(ngram_range=(2,2))
vectorized = count_vect.fit_transform(data["text"])

print(count_vect.vocabulary_)
print(vectorized.toarray())

{'watch the': 3, 'the movie': 2, 'have you': 0, 'you watch': 4, 'movie watch': 1}
[[0 0 1 1 0]
 [1 0 1 1 1]
 [0 1 2 2 0]]


### TFIDF

In [38]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
vectorized = tfidf.fit_transform(data["text"])

print(tfidf.vocabulary_)
print(vectorized.toarray())

{'watch': 3, 'the': 2, 'movie': 1, 'have': 0, 'you': 4}
[[0.         0.57735027 0.57735027 0.57735027 0.        ]
 [0.57292883 0.338381   0.338381   0.338381   0.57292883]
 [0.         0.57735027 0.57735027 0.57735027 0.        ]]
